### ISSUE TITLE
HTTPS communication with openhab fails

### ISSUE THREAD

**Issue by ghost** [unityfire/alexa-ha#11]
When using https for openHAB and configuring config.HA_server as https://... communication between Alexa-HA and openHAB fails. This is due to openHAB shipping with a self signed cert and the request module of nodejs not trusting the CA which signed it.

I have worked around this by adding process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" to openhab.js. This is a very dirty hack though, and should not be used.

Can the code be refactored to support https requests using a non trusted cert? Trusted CA Signed Certs should function correctly now with code as is, though I have not tested this (plan to issue a lets encrypt cert to openHAB and report back).

A possible solution could be Alexa-HA shipping with signing cert for openHAB and refactored to make use of https requests using that cert (or any other self signed cert) when a flag is set? 

I'll look into this and if I come up with a good solution do a pull request. In the mean time, this thing is amazing, thank you so much for the effort!

**Comment by arch1v1st** [comment]
I haven't had a chance to test HTTPS yet, thank you for reporting this issue along with the a workaround.  Rather than shipping with a cert, I would prefer the approach a config option which allows NodeJS/Request to work with a self signed cert.  Thinking this through further.  In the mean time here are some links for reference:
https://loutilities.wordpress.com/2013/04/08/using-ssl-self-signed-certs-with-node-js/
http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

Glad you are liking it!  Many more improvements to come :)

**Comment by arch1v1st** [comment]
Fixed with PR #13, thanks again @noahbeach!
